environment:
  name: webbrowser
  annotate_image: true
  screenshot_delay: 2.0
  viewport_width: 1280
  viewport_height: 1920
  include_poi_text: true
  headless: false
  homepage: https://www.google.co.uk
  keep_original_image: true
solver:
  name: simple
  agent:
    name: proxy_lite
    client:
      name: convergence
      model_id: convergence-ai/proxy-lite
      api_base: https://convergence-ai-demo-api.hf.space/v1
local_view: true
task_timeout: 1800
verbose: true
