repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        files: ^src/
      - id: end-of-file-fixer
        files: ^src/
      - id: check-yaml
        files: ^src/
      - id: check-added-large-files
        files: ^src/
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.3
    hooks:
      - id: ruff
        args: ["--fix"]
        files: ^src/
      - id: ruff-format
        files: ^src/
